/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finiteautomaton;

/**
 *
 * @author Administrator
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtTokens = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtInput = new javax.swing.JTextArea();
        jBtnAnalize = new javax.swing.JButton();
        jBtnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tokens"));

        jTxtTokens.setColumns(20);
        jTxtTokens.setRows(5);
        jTxtTokens.setBorder(null);
        jScrollPane2.setViewportView(jTxtTokens);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        jTxtInput.setColumns(20);
        jTxtInput.setRows(5);
        jTxtInput.setBorder(null);
        jScrollPane3.setViewportView(jTxtInput);

        jBtnAnalize.setText("Analisar");
        jBtnAnalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnalizeActionPerformed(evt);
            }
        });

        jBtnClean.setText("Limpar");
        jBtnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnAnalize)
                        .addGap(4, 4, 4)
                        .addComponent(jBtnClean)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAnalize)
                    .addComponent(jBtnClean))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCleanActionPerformed
        jTxtInput.setText("");
        jTxtTokens.setText("");
    }//GEN-LAST:event_jBtnCleanActionPerformed

    private void jBtnAnalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnalizeActionPerformed
        LexicalAnalyzer la = new LexicalAnalyzer(jTxtInput.getText());
        String text = "";
        for(Token token : la.getTokens()){
            text += token.getType() +": \t" + token.getValue() + "\n";
        }
        jTxtTokens.setText(text);
    }//GEN-LAST:event_jBtnAnalizeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnalize;
    private javax.swing.JButton jBtnClean;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTxtInput;
    private javax.swing.JTextArea jTxtTokens;
    // End of variables declaration//GEN-END:variables
}
